### ISSUE TITLE
BLENDER rendering colorless

### ISSUE THREAD

**Issue by lnbxldn** [crockwell/Cap3D#12]
Hello, after I using the finetuned shap-e to generate objects, I use Captioning_PIPELINE/Render_Script.py to render the objects but I find that the rendered img has no color, what is the reason?
![image](https://github.com/crockwell/Cap3D/assets/49774587/8b2f4fe4-b2ac-4d09-91e5-5eb62183b83b)
![image](https://github.com/crockwell/Cap3D/assets/49774587/f13a40cc-0748-4129-86d3-79baa7e83828)
The first image is a render gif of the object generated by shap-e, and the second image is a render of the OBJ using render_script.py

**Comment by tiangeluo** [comment]
Hi, the rendering code is actually aimed for processing `.glb` files which is the file format for Objaverse objects. It will naturally support processing `.obj` files via `bpy.ops.import_scene.obj(filepath=uid_path)`. However, this blender function seems need `.obj` files be with the material file `.mtl`. Are your `.obj` along with any `.mtl` files?

If your `.obj` file embeds colors as vertex colors, you may need to modify `bpy.ops.import_scene.obj`. 

Alternatively, you should can use shap-E codes to output colorful images. As the default Shap-E rendered images are black background, if you'd like the background be grey (instead of black), you can download our shap-E codes from https://github.com/crockwell/Cap3D/tree/main/text-to-3D/shap-e.

**Comment by tiangeluo** [comment]
How do you store the shap-E output as `.obj` file? Can you make it stored as `.ply` file?

**Comment by lnbxldn** [comment]
> How do you store the shap-E output as `.obj` file? Can you make it stored as `.ply` file?

I use
`
t = decode_latent_mesh(xm, latent).tri_mesh()
        with open(os.path.join(dir_path,'ply',f'{prompt}_{name[:-4]}_{i}.ply'), 'wb') as f:
            t.write_ply(f)
        with open(os.path.join(dir_path,'obj',f'{prompt}_{name[:-4]}_{i}.obj'), 'w') as f:
            t.write_obj(f)
`
to save ply and obj files

**Comment by tiangeluo** [comment]
I just wrote a script for supporting rendering colorful `.ply` results. Please refer to https://github.com/crockwell/Cap3D/blob/main/text-to-3D/shap-e/render_script_shapE.py.

You should can use the above script to render the shapE results. Feel free to let me know if you need further assistance.

**Comment by lnbxldn** [comment]
Thanks to your help and code, ply rendering is OK for now！
