### ISSUE TITLE
How to implement the Shap-E fine tuning part ? 

### ISSUE THREAD

**Issue by Chalos77** [crockwell/Cap3D#6]
Hi ! First of all, thank you very much for your great work! 

I'd like to implement the Shap-E fine tuning code but I don't really understand how to do it. Could you give me more details on the procedure to follow? 

Thanks in advance

**Comment by tiangeluo** [comment]
Hey @Chalos77 ,

I wonder if u could please first refer to https://github.com/crockwell/Cap3D/tree/main/text-to-3D#finetune-shap-e. We have provided the finetune codes along with instructions. I am happy to assistant u if you have further questions after checking the codes.

**Comment by Chalos77** [comment]
Hi @tiangeluo, 

First, thanks for your reply. I have of course carefully read the information provided about Shap-E fine tuning. I did the two first instructions but I don't really understand the third one because on https://huggingface.co/datasets/tiange/Cap3D/tree/main/ShapELatentCode_zips there are around fivety files of 43 GB. Have I to download all of them ? And what do you mean about moving --latent_code_path to the directory you store the shap-E latent code ? Because --latent_code_path is on you finetune_shapE.py file. And where is the train/val file path to modify lines #48,49,68,69 ? 

Thanks in advance

**Comment by tiangeluo** [comment]
Hi @Chalos77,

- You will need shapE latent codes to finetune shapE diffusion models. If you want to use all the latent codes along with our captions, then you need to download all the zip files. Otherwise, you can download parts of them.
- I do not fully understand this question. Once you unzip the files in https://huggingface.co/datasets/tiange/Cap3D/tree/main/ShapELatentCode_zips, you should set up the latent_code_path to the specific directory in your machines.
- Oh, there are errors for the line numbers. I've updated them, thanks! Btw, you can refer to the train/val files in https://github.com/crockwell/Cap3D/tree/main/text-to-3D/example_material.

**Comment by crockwell** [comment]
Closing per inactivity -- feel free to open if there are further questions on this topic!
