### ISSUE TITLE
Code converted to Latent Code

### ISSUE THREAD

**Issue by lnbxldn** [crockwell/Cap3D#7]
Hello, thank you for your wonderful work, but I have encountered a problem. When I want to convert my own dataset into the shape-e latent code, I find that the processing speed is very slow. Could you provide your quick conversion code?

**Comment by lnbxldn** [comment]
Most of the time is spent on converting obj to blender's multiview. If my data are all point cloud npz file, can I directly convert it to the corresponding LatentCode? May I ask what method you used when generating the data? Thanks!

**Comment by tiangeluo** [comment]
Hi @lnbxldn ,

According to the paper and codebase of shapE, we have to use both point clouds and rendered images to obtain the latent codes. Please refer to Figure 2 of https://arxiv.org/pdf/2305.02463.pdf. 

We actually have provided 660k latent codes at our dataset page: https://huggingface.co/datasets/tiange/Cap3D/tree/main/ShapELatentCode_zips. Since I'm using the pre-trained shapE model (by OpenAI) to extract latent codes, there shouldn't be any difference whether you or I generate latent codes. Btw, I have no any quick conversion code.

You can download them and generate the remaining latent codes if needed.

**Comment by lnbxldn** [comment]
> 
Thank you for your reply. There are about 650,000 objects in your dataset. It would take a lot of time to convert them one by one through the official code. It could take weeks or months, how long did it take you to switch?

**Comment by lnbxldn** [comment]
Thank you for your reply. There are about 650,000 objects in your dataset. It would take a lot of time to convert them one by one through the official code. It could take weeks or months, how long did it take you to switch?

**Comment by tiangeluo** [comment]
Hi @lnbxldn,

As we have multiple machines and each machine has multiple gpus, we used 3~4 weeks to done all the 660k code generation.

Btw, install the cuda version FPS could accelerate a bit
https://github.com/crockwell/Cap3D/blob/37a47fd2f1312f874398c30893c7f5898dc443b2/text-to-3D/shap-e/shap_e/rendering/point_cloud.py#L13-L19
