### ISSUE TITLE
Potentially inconsistent captions

### ISSUE THREAD

**Issue by w-hc** [crockwell/Cap3D#9]
Hi thanks for the great work!
I noticed that for some assets the captions seem not that consistent. I was looking at a subset of ~100 high quality assets I selected using some heuristics, and among them these are some strange captions:

| UID                              | Cap3D caption                                                                                                                                                                                                 | SketchFab viewer      |
|----------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------|
| 844ba0cf144a413ea92c779f18912042 | White arrow and line on a gray background.                                                                                                                                                                    | https://skfb.ly/6vLBp |
| 57070b2fd9ff472c8988e76d8c5cbe66 | A 3D model of a futuristic flying robot with wings, resembling a sailboat with a propeller and a helicopter, featuring a large metal structure and a long leg.                                                | https://skfb.ly/6QVvM |
| 23ca8a5c57674b7d984e802e2ed4a436 | "Grey background featuring a white arrow and alternating white and black lines in the middle."                                                                                                                | https://skfb.ly/6RuqR |
| fb40da915b964356938fe59ef300d467 | A 3D model of a giraffe holding a stick, featuring various animal elements such as a dog's leg, deer-like features, a lizard's two legs, a bug's long stick, a long-necked creature, and a horse's long tail. | https://skfb.ly/6RqOy |

The last one was a bit subjective. But the first three feel more like bugs to me, given the very high overall quality of the captions. 
I tried BLIP2 on these four assets and I get 
- a colorful bird with wings spread out
- halo master chief armor
- a 3d rendered man with a yellow glove and a gun
- a 3d rendered deer with antlers

**Comment by crockwell** [comment]
Hello -- thanks for bringing this up! A manual scan of captions on our side shows not all captions are accurate, for sure. Here's a couple things I suspect may be happening:
- One thing that can mess them up is while the asset looks good on SketchFab, it has problems rendering. Have you looked at the (8) rendered images for these examples? 
- Assuming the renders look okay, run BLIP on all 8 views? It might be the case that the forward-facing BLIP caption is good but some other view is not, which could lead to poor examples. Please check all 5 generated BLIP captions for each view. Perhaps some are good or others are not.

**Comment by tiangeluo** [comment]
Hi @w-hc, thank you for bringing this up. Thanks for the brief response, @crockwell.

I have looked into the specific cases. It seems the rendering program failed. For example, 
![57070b2fd9ff472c8988e76d8c5cbe66](https://github.com/crockwell/Cap3D/assets/11552657/85db01d2-cc3a-410d-98f7-c6747213fdc6)

This is indeed a bug in the rendering program. Sorry for any inconvenience caused by this. 

I personally never find this kind of bug previously, and let me think about a possible solution to correct this. Btw, do you have any estimation about the error ratio for relative large samples?

**Comment by w-hc** [comment]
My ranking heuristics was based on `log(viewCount+1) + log(likeCount+1) + 2*log(commentCount+1)`. I was looking at the top100 assets. 

However, based on your rendered images, it looks like the mesh skinning was not applied. It probably helps to focus on the animated assets, of which there are about 40k in objaverse. It's surprising though cuz I thought Blender applies skinning by default.

**Comment by tiangeluo** [comment]
Hi @w-hc , thank you so much for your quick response! 

Could u please share your rendering scripts with me? I also guess it was due to the wrongly applying of transform matrices. Since I have not observed this type of error before, this error should affect a small amount of data. I plan to write a program to detect which objects have such rendering issues and regenerate the captions for those shapes.

**Comment by w-hc** [comment]
I am working with a company for an internship, and so I can't share the code. I am not using Blender, but instead an internal render that trades-off quality for speed. We manually parse .glb files to load the transforms. But I thought Blender shoudn't have this problem to begin with cuz it supports skinning / animation by default.

**Comment by tiangeluo** [comment]
Oh, I see. Thank you for your assistance, Haochen! 

Let me look into the bug this weekend.

**Comment by w-hc** [comment]
I computed the clip cosine similarities on [my own BLIP2 captions - my renderings] and [cap3d_no3d - my renderings], and computed the gaps. Here is a vis plot. 
![clip_score_gap](https://github.com/crockwell/Cap3D/assets/17956191/0bc5a625-4a9f-4d76-a541-ce83a43a96fa)


Here is a picked dump of the data. The format is ``{'uids': list of str, 'cap3d': list of str, 'blip2': list of str, 'gap': torch tensor }``. You can load it with ``torch.load``.  

I think at least the top 6k assets in this comparison need some review. 

https://drive.google.com/file/d/1QttkBOlvv8QOOiH9Bv8qVCSHDWt4T0Rj/view?usp=sharing

**Comment by tiangeluo** [comment]
Hi @w-hc ,

Thank you very much for providing your findings!

I took a look at the file and found three of four uids you provided at the beginning are included in the top 5297 uids (gap > 0.2). However, for some of the objects which have clip gap > 0.2, they are properly rendered. For examples: uid `2da05c03e9c64a91888cf4bcc1ddb9a4` and uid `755039621fca46ca9c2dd70beab2cb52`.

![2da05c03e9c64a91888cf4bcc1ddb9a4_0](https://github.com/crockwell/Cap3D/assets/11552657/1a533337-13da-43f3-a988-aa1c935b34d
![755039621fca46ca9c2dd70beab2cb52_0](https://github.com/crockwell/Cap3D/assets/11552657/095b80e2-0edb-43df-83db-66d8f1638aee)
9)

Since the re-render only covers ~6k objects, I plan to re-run the whole captioning process and update captions/rendering images soon. 

Thanks again!

**Comment by tiangeluo** [comment]
Hi @w-hc ,

Thank you very much for your assistance!

Based on your findings and my inspection of some defective renderings, I've updated a total of `6,893` captions, including `5,297` objects you suggested. It occupies `6893/661577 = 1.04%` of the entire dataset. 

I've update the new caption here: https://huggingface.co/datasets/tiange/Cap3D/resolve/main/Cap3D_automated_Objaverse.csv. The specific updates are listed: [Cap3d_captions_fix_110123.csv](https://github.com/crockwell/Cap3D/files/13230288/Cap3d_captions_fix_110123.csv). 

Thanks again, and please let me know if you notice other issues! Btw, do you mind me including you in the acknowledgement section of this repo?

**Comment by w-hc** [comment]
@tiangeluo thanks a lot for the help and contribution. And I'm grateful to be included in acknowledgements.

**Comment by crockwell** [comment]
Closing per inactivity -- feel free to open if there are further questions on this topic!
